### ISSUE TITLE
Things to-do - Week 03/14 - 03/21

### ISSUE THREAD

**Issue by angelip2303** [Arquisoft/dede_en2a#116]
### Prototype v0.1 - Unfinished work

- [x] Add more products to the database
- [x] Add the home page
- [x] Store the WebID of authenticated users, removing: name, surname and email from the sign-up page.
- [x] Don't allow users to go to the next step without paying
- [x] Use verification token for the request

### Prototype v0.1 - Bugs

- [x] Ratings are not shown properly when the window is shrunken
- [x] Show a loading feedback when calculating the shipping costs
- [x] Update the stock when the user pays, we should not expect him to press _Finish_
- [x] Breadcrumbs are not working as they should: _Shopping_ is not a page of the site
- [x] When moved to _Billing info_ in checkout the shipping costs are recalculated, that shouldn't happen
- [x] User should be redirected to home when presses the home button on checkout
- [x] In the orders listing of the user control panel, the message should be something like: "Your orders, {name}"
- [x] Store the user in session properly
- [x] Restore the cart when user logs out
- [x] Show products in columns depending on the width of the device
- [x] Add vertical padding to each item of the product listing
- [ ] Change product update after order to backend

### Documentation 
- [ ] Model of the persistence system
- [ ] Add the APIs we are using to the business context
- [ ] Update the technology stack
- [ ] Format the technology stack as a table
- [ ] Update _Building Block View_ diagrams
