### ISSUE TITLE
Things to-do - Week 03/21 - 03/28

### ISSUE THREAD

**Issue by uo271580** [Arquisoft/dede_en2a#128]
- [ ] Product update on restapi
- [x] Messages when POD is access
- [x] Create products
- [x] Manage roles
- [ ] Start with tests
- [x] Deploy docker
- [x] Deny next step on checkout
- [x] Redirecting routes
- [ ] Store addresses in orders
- [x] Delete product image when deleting product
