### ISSUE TITLE
Things to-do - Week 03/28 - 04/04

### ISSUE THREAD

**Issue by angelip2303** [Arquisoft/dede_en2a#148]
### Prototype v0.1 - Bugs

- [x]  Change product update after order to backend

### Prototype v1.0

- [x] Update products on REST api
- [x] Start testing the app
- [x] Deploy the app using Docker
- [x] Store the address in the order itself
- [x] Hide some functionalities of the Dashboard for certain roles
- [x] Change the way we show the NavBar depending on the width of the device
- [x] Check why they are not working the ADD + and DELETE - buttons
- [x] Check that the graph works just fine
- [x] Improve the UI of the Dashboard
- [x] Fix the BACK/NEXT buttons of the checkout page
- [x] Show a better message when the user is not validated
- [x] Wait for orders to load with a tiny animation
- [x] Fix the order filter so it works as intended
- [x] Add the city and post code to the street address when retrieved from SOLID 
- [x] Add some functionality to the graph
- [x] BUG: Fix the routes and breadcrumbs  
- [x] BUG: Upload and Delete product not working
- [x] BUG: Pagination not working
- [x] BUG: Order filtering not working

### Documentation v0.1 - Improvements

- [ ] Model of the persistence system
- [ ] Add the APIs we are using to the business context
- [ ] Update the technology stack
- [x] Format the technology stack as a table
- [x] Update _Building Block View_ diagrams
- [x] Keep updating the ADR in Section 9

### Documentation v1.0

- [x] SECTION 7: Deployment view
- [x] SECTION 8: Cross-cutting concepts
- [x] SECTION 10: Quality requirements
- [x] SECTION 11: Risks and technology debts
- [x] SECTION 12: Glossary
