### ISSUE TITLE
Things to-do for the last delivery

### ISSUE THREAD

**Issue by angelip2303** [Arquisoft/dede_en2a#230]
### Responsive design

- [ ] Improve the looks of the product details page: ratings overlap the container and the button on the bottom is not properly placed.
- [ ] Shopping cart needs improvements. The image and product name are not quite responsive.
- [ ] In the billing section, the back button should be placed to the left. We should take a look at all the buttons.

### Prototype v1.0 - Bug fixing and Improvements

- [ ] Improve the way we limit users with no privilege to access some parts of the application.
- [ ] Improve the security of the requests in the backend.
- [ ] Use the external API for calculating the shipping prices with different carriers.
- [ ] Fix the rating bugs: the button must be pressed twice in order the dialog to appear and you must reload the page for the rating to be included.
- [ ] Move the focus to the top when we press next on the pagination.
- [ ] Test the application reaching a higher coverage.

### Prototype v1.1 - New features

- [ ] Allow user to modify data from their POD directly from the APP. Information such as the address should be modifiable.
- [ ] Edit a products, a new feature for moderator and above roles.
- [ ] Sort products by categories.
- [ ] Filter products by their price.
- [ ] Allow packages to ship from different warehouses, now we only provide the possibility for the item to be shipped from one address: the school.
- [ ] Add a notifications feature inside the application (can take the shape of a bell on the navigation bar) where the user can keep track of his opened orders.
- [ ] Allow the user to choose his favorite products and be able to take a look at them in the dashboard.

**Comment by uo271580** [comment]
I research a bit for memoization solution but i think it is not worth it doing it since products may change their amount constantly based on other users' orders. Maybe for orders or users can be possible since they don't change

**Comment by angelip2303** [comment]
@uo271580 nice point I didn't consider that. Probably we could take a look for some minor improvements using memoization eitherway!
