### ISSUE TITLE
Things to-do for the last week :(

### ISSUE THREAD

**Issue by angelip2303** [Arquisoft/dede_en2a#248]
### Front-end

- [x] Show error messages when unexpected behavior happens: no email, no address (in the POD)...
- [x] Add an autocomplete for the user to choose the product to delete.
- [x] Don't allow user to modify the code when adding a new product.
- [x] Add a back button for the user to go back when a modifying products: add, update and delete.
- [x] Fix how we manage the ratings: if a review has already been submitted allow the user to edit. Check what happens when the user is not logged in.
- [x] Auto-reload ratings when a new one is included.
- [x] Allow user to modify his address directly from the application.
- [x] Allow user - in case he has no addresses on the POD - to add a new one.
- [x] Improve the way cards are shown.
- [x] Sort products by categories.
- [x] Filter products by their price.
- [x] Check what happens when SOLID login fails: no internet connection.
- [x] Make login page redirect to the actual page where the user was before trying to sign-in.
- [x] Show addresses from POD on reload. 

### Back-end

- [x] Allow users to download a PDF with the details of their order.

### Minor bug fixing and improvements

- [x] Handle the exceptions that are prompted in the console.
- [x] Make sure that graphs are properly displayed.
- [x] Round prices to two decimal places.
- [x] Fix the order listing for individual users.
- [x] Fix the errors prompted by the sonarcloud.

### Documentation v1.0 - Things we missed :(

- [x] Model of the persistence system
- [x] Update the technology stack

### Documentation v1.1 - Improvements

- [x]  Revisit the documentation for it to be perfect :_)
