### ISSUE TITLE
Things to-do before second delivery

### ISSUE THREAD

**Issue by angelip2303** [Arquisoft/dede_en2a#97]
### Documentation related topics

- [x] Keep improving what we had to do in the first delivery. For further details: #52. 

### Prototype v0.1

- [x] Improve the way orders are shown.
- [x] Add the "See details" button in the orders page.
- [x] Improve the way product details are shown.
- [x] Improve how we show the different ratings users give.
- [x] Store orders in the database when they are processed.
- [x] Reset the session of the cart to 0 when the order is processed.
- [x] Add more stuff to the DB.
- [x] Forbidden access to some parts of the page: checkout.
- [x] Move orders page to a _user control panel_ site.
- [x] Allow only authenticated users to access their orders.
- [x] Add the home page.
- [x] Store the WebID of authenticated users and remove name/surname/email in two steps: first write the WebID and then you are requested to accept the changes.
- [x] In the checkout page we shouldn't allow users to go to the next step without paying.

### I made something

- [x] Start working with [Docker](https://www.docker.com/) and the deployment system.
- [x] Start researching on testing for this kind of projects.
